apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebpf-agent
  labels:
    app: ebpf-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebpf-agent
  template:
    metadata:
      labels:
        app: ebpf-agent
    spec:
      # the agent must be privileged
      hostNetwork: true
      # needed to allow resolving collector hostname
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: netobserv-ebpf-agent
          image: quay.io/netobserv/netobserv-ebpf-agent:2d63d90
          securityContext:
            privileged: true
            runAsUser: 0
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: EXPORT
              value: "grpc"
            - name: FLOWS_TARGET_HOST
              value: "flowlogs-pipeline"
            - name: FLOWS_TARGET_PORT
              value: "2055"

